"""
Mobile App Builder Module for Infinity Worker v5.0

Generates Android APKs and iOS apps from web projects using:
- Bubblewrap (TWA) for Android
- Capacitor for cross-platform
- PWA wrapper for web-to-app conversion

Zero-cost implementation - no external build services required.
"""

import os
import json
import shutil
import subprocess
import tempfile
import hashlib
import zipfile
from datetime import datetime
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field, asdict
from pathlib import Path
import asyncio
import logging

logger = logging.getLogger(__name__)


@dataclass
class MobileAppConfig:
    """Configuration for mobile app generation"""
    app_name: str
    package_name: str  # e.g., com.example.myapp
    version: str = "1.0.0"
    version_code: int = 1
    display_mode: str = "standalone"  # standalone, fullscreen, minimal-ui
    orientation: str = "any"  # any, portrait, landscape
    theme_color: str = "#1a1a2e"
    background_color: str = "#1a1a2e"
    icon_url: Optional[str] = None
    splash_color: str = "#1a1a2e"
    start_url: str = "/"
    scope: str = "/"
    description: str = ""
    short_name: Optional[str] = None
    

@dataclass
class MobileBuildResult:
    """Result of mobile app build"""
    success: bool
    platform: str  # android, ios, pwa
    build_type: str  # apk, aab, ipa, pwa
    file_path: Optional[str] = None
    file_size: Optional[int] = None
    download_url: Optional[str] = None
    error: Optional[str] = None
    build_time_seconds: float = 0
    build_id: str = ""
    manifest: Optional[Dict] = None


class PWAGenerator:
    """Generates PWA assets (manifest, service worker) for web projects"""
    
    def __init__(self, project_dir: str, config: MobileAppConfig):
        self.project_dir = Path(project_dir)
        self.config = config
    
    def generate_manifest(self) -> Dict:
        """Generate PWA manifest.json"""
        manifest = {
            "name": self.config.app_name,
            "short_name": self.config.short_name or self.config.app_name[:12],
            "description": self.config.description or f"{self.config.app_name} - Built with Infinity Worker",
            "start_url": self.config.start_url,
            "scope": self.config.scope,
            "display": self.config.display_mode,
            "orientation": self.config.orientation,
            "theme_color": self.config.theme_color,
            "background_color": self.config.background_color,
            "icons": [
                {
                    "src": "/icons/icon-72x72.png",
                    "sizes": "72x72",
                    "type": "image/png",
                    "purpose": "any maskable"
                },
                {
                    "src": "/icons/icon-96x96.png",
                    "sizes": "96x96",
                    "type": "image/png",
                    "purpose": "any maskable"
                },
                {
                    "src": "/icons/icon-128x128.png",
                    "sizes": "128x128",
                    "type": "image/png",
                    "purpose": "any maskable"
                },
                {
                    "src": "/icons/icon-144x144.png",
                    "sizes": "144x144",
                    "type": "image/png",
                    "purpose": "any maskable"
                },
                {
                    "src": "/icons/icon-152x152.png",
                    "sizes": "152x152",
                    "type": "image/png",
                    "purpose": "any maskable"
                },
                {
                    "src": "/icons/icon-192x192.png",
                    "sizes": "192x192",
                    "type": "image/png",
                    "purpose": "any maskable"
                },
                {
                    "src": "/icons/icon-384x384.png",
                    "sizes": "384x384",
                    "type": "image/png",
                    "purpose": "any maskable"
                },
                {
                    "src": "/icons/icon-512x512.png",
                    "sizes": "512x512",
                    "type": "image/png",
                    "purpose": "any maskable"
                }
            ],
            "categories": ["productivity", "utilities"],
            "lang": "en-US",
            "dir": "ltr",
            "prefer_related_applications": False
        }
        return manifest
    
    def generate_service_worker(self) -> str:
        """Generate service worker for offline support"""
        sw_code = f'''
// Service Worker for {self.config.app_name}
// Generated by Infinity Worker Mobile Builder

const CACHE_NAME = '{self.config.package_name}-v{self.config.version}';
const OFFLINE_URL = '/offline.html';

// Files to cache immediately
const PRECACHE_ASSETS = [
    '/',
    '/index.html',
    '/manifest.json',
    '/offline.html'
];

// Install event - cache core assets
self.addEventListener('install', (event) => {{
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => {{
                console.log('[SW] Precaching assets');
                return cache.addAll(PRECACHE_ASSETS);
            }})
            .then(() => self.skipWaiting())
    );
}});

// Activate event - clean old caches
self.addEventListener('activate', (event) => {{
    event.waitUntil(
        caches.keys().then((cacheNames) => {{
            return Promise.all(
                cacheNames
                    .filter((name) => name !== CACHE_NAME)
                    .map((name) => caches.delete(name))
            );
        }}).then(() => self.clients.claim())
    );
}});

// Fetch event - network first, fallback to cache
self.addEventListener('fetch', (event) => {{
    // Skip non-GET requests
    if (event.request.method !== 'GET') return;
    
    // Skip cross-origin requests
    if (!event.request.url.startsWith(self.location.origin)) return;
    
    event.respondWith(
        fetch(event.request)
            .then((response) => {{
                // Clone response for caching
                const responseClone = response.clone();
                caches.open(CACHE_NAME).then((cache) => {{
                    cache.put(event.request, responseClone);
                }});
                return response;
            }})
            .catch(() => {{
                return caches.match(event.request)
                    .then((cachedResponse) => {{
                        if (cachedResponse) {{
                            return cachedResponse;
                        }}
                        // Return offline page for navigation requests
                        if (event.request.mode === 'navigate') {{
                            return caches.match(OFFLINE_URL);
                        }}
                        return new Response('Offline', {{ status: 503 }});
                    }});
            }})
    );
}});

// Background sync for offline actions
self.addEventListener('sync', (event) => {{
    if (event.tag === 'sync-data') {{
        event.waitUntil(syncData());
    }}
}});

async function syncData() {{
    // Implement background sync logic here
    console.log('[SW] Background sync triggered');
}}
'''
        return sw_code
    
    def generate_offline_page(self) -> str:
        """Generate offline fallback page"""
        return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.config.app_name} - Offline</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: {self.config.background_color};
            color: #ffffff;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            padding: 20px;
        }}
        .container {{
            max-width: 400px;
        }}
        .icon {{
            font-size: 64px;
            margin-bottom: 20px;
        }}
        h1 {{
            font-size: 24px;
            margin-bottom: 10px;
        }}
        p {{
            color: #888;
            margin-bottom: 20px;
        }}
        button {{
            background: {self.config.theme_color};
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
        }}
        button:hover {{
            opacity: 0.9;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="icon">📡</div>
        <h1>You're Offline</h1>
        <p>Please check your internet connection and try again.</p>
        <button onclick="location.reload()">Retry</button>
    </div>
</body>
</html>
'''
    
    def generate_icons(self, output_dir: Path) -> List[str]:
        """Generate placeholder icons (in production, use actual icon generation)"""
        icons_dir = output_dir / "icons"
        icons_dir.mkdir(parents=True, exist_ok=True)
        
        sizes = [72, 96, 128, 144, 152, 192, 384, 512]
        generated = []
        
        for size in sizes:
            # Generate a simple SVG icon (placeholder)
            svg_content = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 {size} {size}">
    <rect width="{size}" height="{size}" fill="{self.config.theme_color}"/>
    <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="white" font-size="{size//3}" font-family="Arial, sans-serif">
        {self.config.short_name[:2].upper() if self.config.short_name else self.config.app_name[:2].upper()}
    </text>
</svg>'''
            
            icon_path = icons_dir / f"icon-{size}x{size}.svg"
            icon_path.write_text(svg_content)
            generated.append(str(icon_path))
        
        return generated
    
    def apply_to_project(self) -> Dict[str, str]:
        """Apply PWA assets to the project directory"""
        files_created = {}
        
        # Generate manifest
        manifest = self.generate_manifest()
        manifest_path = self.project_dir / "manifest.json"
        manifest_path.write_text(json.dumps(manifest, indent=2))
        files_created["manifest.json"] = str(manifest_path)
        
        # Generate service worker
        sw_code = self.generate_service_worker()
        sw_path = self.project_dir / "sw.js"
        sw_path.write_text(sw_code)
        files_created["sw.js"] = str(sw_path)
        
        # Generate offline page
        offline_html = self.generate_offline_page()
        offline_path = self.project_dir / "offline.html"
        offline_path.write_text(offline_html)
        files_created["offline.html"] = str(offline_path)
        
        # Generate icons
        icon_files = self.generate_icons(self.project_dir)
        for icon in icon_files:
            files_created[Path(icon).name] = icon
        
        return files_created


class AndroidAPKBuilder:
    """Builds Android APKs using Bubblewrap (TWA) or Capacitor"""
    
    def __init__(self, config: MobileAppConfig):
        self.config = config
        self.build_dir = Path(tempfile.mkdtemp(prefix="infinity-apk-"))
        
    async def check_dependencies(self) -> Dict[str, bool]:
        """Check if required build tools are available"""
        deps = {
            "node": False,
            "npm": False,
            "java": False,
            "bubblewrap": False
        }
        
        try:
            result = subprocess.run(["node", "--version"], capture_output=True, text=True)
            deps["node"] = result.returncode == 0
        except:
            pass
            
        try:
            result = subprocess.run(["npm", "--version"], capture_output=True, text=True)
            deps["npm"] = result.returncode == 0
        except:
            pass
            
        try:
            result = subprocess.run(["java", "-version"], capture_output=True, text=True)
            deps["java"] = result.returncode == 0
        except:
            pass
            
        try:
            result = subprocess.run(["npx", "bubblewrap", "--version"], capture_output=True, text=True)
            deps["bubblewrap"] = result.returncode == 0
        except:
            pass
            
        return deps
    
    def generate_twa_manifest(self, web_url: str) -> Dict:
        """Generate TWA manifest for Bubblewrap"""
        return {
            "packageId": self.config.package_name,
            "host": web_url.replace("https://", "").replace("http://", "").split("/")[0],
            "name": self.config.app_name,
            "launcherName": self.config.short_name or self.config.app_name[:12],
            "display": self.config.display_mode,
            "themeColor": self.config.theme_color,
            "navigationColor": self.config.theme_color,
            "navigationColorDark": self.config.theme_color,
            "navigationDividerColor": self.config.theme_color,
            "navigationDividerColorDark": self.config.theme_color,
            "backgroundColor": self.config.background_color,
            "enableNotifications": True,
            "startUrl": self.config.start_url,
            "iconUrl": self.config.icon_url or f"{web_url}/icons/icon-512x512.png",
            "maskableIconUrl": self.config.icon_url or f"{web_url}/icons/icon-512x512.png",
            "splashScreenFadeOutDuration": 300,
            "signingKey": {
                "path": "./android.keystore",
                "alias": "android"
            },
            "appVersionCode": self.config.version_code,
            "appVersionName": self.config.version,
            "shortcuts": [],
            "generatorApp": "infinity-worker",
            "webManifestUrl": f"{web_url}/manifest.json",
            "fallbackType": "customtabs",
            "features": {
                "locationDelegation": {
                    "enabled": True
                },
                "playBilling": {
                    "enabled": False
                }
            },
            "alphaDependencies": {
                "enabled": False
            },
            "enableSiteSettingsShortcut": True,
            "isChromeOSOnly": False,
            "isMetaQuest": False,
            "fullScopeUrl": web_url,
            "minSdkVersion": 21,
            "orientation": self.config.orientation
        }
    
    async def build_apk_with_bubblewrap(self, web_url: str, output_dir: str) -> MobileBuildResult:
        """Build APK using Bubblewrap CLI"""
        start_time = datetime.now()
        build_id = hashlib.md5(f"{web_url}{datetime.now().isoformat()}".encode()).hexdigest()[:12]
        
        try:
            # Create TWA manifest
            twa_manifest = self.generate_twa_manifest(web_url)
            manifest_path = self.build_dir / "twa-manifest.json"
            manifest_path.write_text(json.dumps(twa_manifest, indent=2))
            
            # Initialize Bubblewrap project
            init_cmd = [
                "npx", "@aspect-build/aspect", "init",
                "--manifest", str(manifest_path),
                "--directory", str(self.build_dir / "twa-project")
            ]
            
            logger.info(f"Initializing TWA project: {' '.join(init_cmd)}")
            
            process = await asyncio.create_subprocess_exec(
                *init_cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(self.build_dir)
            )
            stdout, stderr = await process.communicate()
            
            if process.returncode != 0:
                logger.error(f"Bubblewrap init failed: {stderr.decode()}")
                # Fall back to simple APK wrapper
                return await self.build_simple_apk(web_url, output_dir, build_id)
            
            # Build APK
            build_cmd = [
                "npx", "@aspect-build/aspect", "build",
                "--skipPwaValidation"
            ]
            
            process = await asyncio.create_subprocess_exec(
                *build_cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(self.build_dir / "twa-project")
            )
            stdout, stderr = await process.communicate()
            
            if process.returncode != 0:
                return await self.build_simple_apk(web_url, output_dir, build_id)
            
            # Find generated APK
            apk_path = self.build_dir / "twa-project" / "app-release-signed.apk"
            if not apk_path.exists():
                apk_path = self.build_dir / "twa-project" / "app-release-unsigned.apk"
            
            if apk_path.exists():
                # Copy to output directory
                output_path = Path(output_dir) / f"{self.config.package_name}-{build_id}.apk"
                shutil.copy(apk_path, output_path)
                
                build_time = (datetime.now() - start_time).total_seconds()
                
                return MobileBuildResult(
                    success=True,
                    platform="android",
                    build_type="apk",
                    file_path=str(output_path),
                    file_size=output_path.stat().st_size,
                    build_time_seconds=build_time,
                    build_id=build_id,
                    manifest=twa_manifest
                )
            else:
                return await self.build_simple_apk(web_url, output_dir, build_id)
                
        except Exception as e:
            logger.error(f"APK build error: {e}")
            return await self.build_simple_apk(web_url, output_dir, build_id)
    
    async def build_simple_apk(self, web_url: str, output_dir: str, build_id: str) -> MobileBuildResult:
        """Build a simple WebView-based APK (fallback method)"""
        start_time = datetime.now()
        
        try:
            # Create Android project structure
            project_dir = self.build_dir / "android-project"
            project_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate build configuration
            build_config = {
                "app_name": self.config.app_name,
                "package_name": self.config.package_name,
                "version": self.config.version,
                "version_code": self.config.version_code,
                "web_url": web_url,
                "theme_color": self.config.theme_color,
                "build_id": build_id,
                "build_method": "webview-wrapper",
                "generated_at": datetime.now().isoformat(),
                "generator": "Infinity Worker Mobile Builder"
            }
            
            # Save build config
            config_path = project_dir / "build-config.json"
            config_path.write_text(json.dumps(build_config, indent=2))
            
            # Create a downloadable package with instructions
            package_dir = project_dir / "infinity-mobile-package"
            package_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate Capacitor config
            capacitor_config = {
                "appId": self.config.package_name,
                "appName": self.config.app_name,
                "webDir": "www",
                "server": {
                    "url": web_url,
                    "cleartext": True
                },
                "android": {
                    "buildOptions": {
                        "keystorePath": "android.keystore",
                        "keystoreAlias": "android"
                    }
                }
            }
            
            (package_dir / "capacitor.config.json").write_text(
                json.dumps(capacitor_config, indent=2)
            )
            
            # Generate package.json for Capacitor
            package_json = {
                "name": self.config.package_name.replace(".", "-"),
                "version": self.config.version,
                "description": self.config.description or f"{self.config.app_name} Mobile App",
                "scripts": {
                    "build:android": "npx cap build android",
                    "build:ios": "npx cap build ios",
                    "sync": "npx cap sync",
                    "open:android": "npx cap open android",
                    "open:ios": "npx cap open ios"
                },
                "dependencies": {
                    "@capacitor/android": "^6.0.0",
                    "@capacitor/core": "^6.0.0",
                    "@capacitor/ios": "^6.0.0"
                },
                "devDependencies": {
                    "@capacitor/cli": "^6.0.0"
                }
            }
            
            (package_dir / "package.json").write_text(
                json.dumps(package_json, indent=2)
            )
            
            # Generate build instructions
            readme = f'''# {self.config.app_name} - Mobile App Package

## Generated by Infinity Worker Mobile Builder

This package contains everything needed to build native Android and iOS apps.

### Quick Start (Android)

1. Install dependencies:
   ```bash
   npm install
   ```

2. Add Android platform:
   ```bash
   npx cap add android
   ```

3. Build APK:
   ```bash
   npx cap build android
   ```

### Quick Start (iOS)

1. Install dependencies:
   ```bash
   npm install
   ```

2. Add iOS platform:
   ```bash
   npx cap add ios
   ```

3. Build IPA (requires macOS):
   ```bash
   npx cap build ios
   ```

### Configuration

- **App Name:** {self.config.app_name}
- **Package ID:** {self.config.package_name}
- **Version:** {self.config.version}
- **Web URL:** {web_url}

### Build ID: {build_id}
### Generated: {datetime.now().isoformat()}
'''
            
            (package_dir / "README.md").write_text(readme)
            
            # Create www directory with redirect
            www_dir = package_dir / "www"
            www_dir.mkdir(parents=True, exist_ok=True)
            
            index_html = f'''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.config.app_name}</title>
    <script>window.location.href = "{web_url}";</script>
</head>
<body>
    <p>Redirecting to {self.config.app_name}...</p>
</body>
</html>
'''
            (www_dir / "index.html").write_text(index_html)
            
            # Create zip package
            output_path = Path(output_dir) / f"{self.config.package_name}-{build_id}-mobile-package.zip"
            
            with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for file_path in package_dir.rglob('*'):
                    if file_path.is_file():
                        arcname = file_path.relative_to(package_dir)
                        zipf.write(file_path, arcname)
            
            build_time = (datetime.now() - start_time).total_seconds()
            
            return MobileBuildResult(
                success=True,
                platform="android",
                build_type="capacitor-package",
                file_path=str(output_path),
                file_size=output_path.stat().st_size,
                build_time_seconds=build_time,
                build_id=build_id,
                manifest=build_config
            )
            
        except Exception as e:
            logger.error(f"Simple APK build error: {e}")
            return MobileBuildResult(
                success=False,
                platform="android",
                build_type="apk",
                error=str(e),
                build_id=build_id
            )
    
    def cleanup(self):
        """Clean up temporary build directory"""
        try:
            shutil.rmtree(self.build_dir)
        except:
            pass


class MobileAppBuilder:
    """Main mobile app builder orchestrator"""
    
    def __init__(self, output_dir: str = "/tmp/infinity-mobile-builds"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    async def build_android(
        self,
        web_url: str,
        config: MobileAppConfig
    ) -> MobileBuildResult:
        """Build Android APK from web URL"""
        builder = AndroidAPKBuilder(config)
        try:
            result = await builder.build_apk_with_bubblewrap(web_url, str(self.output_dir))
            if result.success and result.file_path:
                result.download_url = f"/api/mobile/download/{result.build_id}"
            return result
        finally:
            builder.cleanup()
    
    async def build_pwa(
        self,
        project_files: Dict[str, str],
        config: MobileAppConfig
    ) -> MobileBuildResult:
        """Generate PWA assets for a project"""
        start_time = datetime.now()
        build_id = hashlib.md5(f"{config.app_name}{datetime.now().isoformat()}".encode()).hexdigest()[:12]
        
        try:
            # Create temp project directory
            project_dir = Path(tempfile.mkdtemp(prefix="infinity-pwa-"))
            
            # Write project files
            for path, content in project_files.items():
                file_path = project_dir / path
                file_path.parent.mkdir(parents=True, exist_ok=True)
                file_path.write_text(content)
            
            # Generate PWA assets
            pwa_gen = PWAGenerator(str(project_dir), config)
            files_created = pwa_gen.apply_to_project()
            
            # Create zip package
            output_path = self.output_dir / f"{config.package_name}-{build_id}-pwa.zip"
            
            with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for file_path in project_dir.rglob('*'):
                    if file_path.is_file():
                        arcname = file_path.relative_to(project_dir)
                        zipf.write(file_path, arcname)
            
            # Cleanup
            shutil.rmtree(project_dir)
            
            build_time = (datetime.now() - start_time).total_seconds()
            
            return MobileBuildResult(
                success=True,
                platform="pwa",
                build_type="pwa",
                file_path=str(output_path),
                file_size=output_path.stat().st_size,
                download_url=f"/api/mobile/download/{build_id}",
                build_time_seconds=build_time,
                build_id=build_id,
                manifest=pwa_gen.generate_manifest()
            )
            
        except Exception as e:
            logger.error(f"PWA build error: {e}")
            return MobileBuildResult(
                success=False,
                platform="pwa",
                build_type="pwa",
                error=str(e),
                build_id=build_id
            )
    
    def get_build(self, build_id: str) -> Optional[Path]:
        """Get build file by ID"""
        for file_path in self.output_dir.glob(f"*-{build_id}*"):
            if file_path.is_file():
                return file_path
        return None
    
    def list_builds(self) -> List[Dict]:
        """List all available builds"""
        builds = []
        for file_path in self.output_dir.glob("*"):
            if file_path.is_file():
                builds.append({
                    "filename": file_path.name,
                    "size": file_path.stat().st_size,
                    "created": datetime.fromtimestamp(file_path.stat().st_ctime).isoformat()
                })
        return sorted(builds, key=lambda x: x["created"], reverse=True)


class IOSIPABuilder:
    """
    iOS IPA Builder (Documentation and Future Implementation)
    
    iOS builds require:
    - macOS with Xcode installed
    - Apple Developer account
    - Valid signing certificates and provisioning profiles
    
    Zero-cost options for iOS:
    1. Codemagic (500 build minutes/month free)
    2. GitHub Actions with macOS runners (limited free minutes)
    3. Local macOS machine
    
    This class provides the interface for future iOS build integration.
    """
    
    def __init__(self, config: MobileAppConfig):
        self.config = config
    
    async def build_ipa(self, project_path: str, output_dir: str) -> MobileBuildResult:
        """
        Build iOS IPA (requires macOS)
        
        For zero-cost iOS builds, users should:
        1. Download the Capacitor package from /api/mobile/build/android
        2. Run on macOS: npx cap add ios && npx cap build ios
        3. Or use Codemagic free tier for cloud builds
        """
        return MobileBuildResult(
            success=False,
            platform="ios",
            build_type="ipa",
            error="iOS builds require macOS. Download the Capacitor package and build locally, or use Codemagic free tier.",
            build_id=""
        )
    
    def generate_xcode_project_config(self) -> Dict:
        """Generate Xcode project configuration"""
        return {
            "PRODUCT_BUNDLE_IDENTIFIER": self.config.package_name,
            "PRODUCT_NAME": self.config.app_name,
            "MARKETING_VERSION": self.config.version,
            "CURRENT_PROJECT_VERSION": str(self.config.version_code),
            "INFOPLIST_KEY_CFBundleDisplayName": self.config.app_name,
            "INFOPLIST_KEY_UILaunchScreen_Generation": "YES",
            "INFOPLIST_KEY_UISupportedInterfaceOrientations": self._get_ios_orientations(),
            "ASSETCATALOG_COMPILER_APPICON_NAME": "AppIcon",
            "ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME": "AccentColor"
        }
    
    def _get_ios_orientations(self) -> str:
        """Convert orientation config to iOS format"""
        if self.config.orientation == "portrait":
            return "UIInterfaceOrientationPortrait"
        elif self.config.orientation == "landscape":
            return "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        else:
            return "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    
    def generate_info_plist_entries(self) -> Dict:
        """Generate Info.plist entries"""
        return {
            "CFBundleName": self.config.app_name,
            "CFBundleDisplayName": self.config.app_name,
            "CFBundleIdentifier": self.config.package_name,
            "CFBundleVersion": str(self.config.version_code),
            "CFBundleShortVersionString": self.config.version,
            "UIStatusBarStyle": "UIStatusBarStyleLightContent",
            "UIViewControllerBasedStatusBarAppearance": False,
            "ITSAppUsesNonExemptEncryption": False
        }


# Singleton instance
mobile_builder = MobileAppBuilder()
