"""initial schema — 27 tables

Revision ID: 894366a8346d
Revises: 
Create Date: 2026-02-25 04:29:55.557648

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894366a8346d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_manifests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('author_url', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('entry_point', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('min_kernel_version', sa.String(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('is_built_in', sa.Boolean(), nullable=True),
    sa.Column('is_sandboxed', sa.Boolean(), nullable=True),
    sa.Column('privacy_policy_url', sa.String(), nullable=True),
    sa.Column('support_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_manifests_category'), 'module_manifests', ['category'], unique=False)
    op.create_index(op.f('ix_module_manifests_module_id'), 'module_manifests', ['module_id'], unique=True)
    op.create_table('organisations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='orgplan'), nullable=False),
    sa.Column('region_iso_code', sa.String(), nullable=True),
    sa.Column('compliance_tier', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_deleted', 'organisations', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_organisations_is_active'), 'organisations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.create_table('ai_systems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('risk_level', sa.Enum('PROHIBITED', 'HIGH_RISK', 'LIMITED_RISK', 'MINIMAL_RISK', name='risklevel'), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('model_ids', sa.JSON(), nullable=True),
    sa.Column('human_oversight_level', sa.String(), nullable=True),
    sa.Column('transparency_measures', sa.JSON(), nullable=True),
    sa.Column('dpia_completed', sa.Boolean(), nullable=True),
    sa.Column('dpia_details', sa.JSON(), nullable=True),
    sa.Column('last_audit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_system_org_status', 'ai_systems', ['organisation_id', 'compliance_status'], unique=False)
    op.create_index(op.f('ix_ai_systems_compliance_status'), 'ai_systems', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_ai_systems_created_at'), 'ai_systems', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_systems_dpia_completed'), 'ai_systems', ['dpia_completed'], unique=False)
    op.create_index(op.f('ix_ai_systems_name'), 'ai_systems', ['name'], unique=False)
    op.create_index(op.f('ix_ai_systems_organisation_id'), 'ai_systems', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ai_systems_risk_level'), 'ai_systems', ['risk_level'], unique=False)
    op.create_table('app_store_listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manifest_id', sa.String(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='modulestatus'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['module_manifests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('federated_services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('health_check_url', sa.String(), nullable=True),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('auth_credentials_ref', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fed_org_type', 'federated_services', ['organisation_id', 'service_type'], unique=False)
    op.create_index(op.f('ix_federated_services_organisation_id'), 'federated_services', ['organisation_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'AUDITOR', 'POWER_USER', 'USER', name='userrole'), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_deleted', 'users', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_user_org_active', 'users', ['organisation_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_organisation_id'), 'api_keys', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.Enum('GENERATION_SUCCESS', 'GENERATION_FAILED', 'GOVERNANCE_REJECTED', 'DPIA_COMPLETED', 'DPIA_APPROVED', 'PROVENANCE_SIGNED', 'SYSTEM_REGISTERED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTER', 'USER_INVITED', 'USER_ROLE_CHANGED', 'USER_DEACTIVATED', 'PASSWORD_RESET', 'TOKEN_REVOKED', 'MODEL_ENABLED', 'MODEL_DISABLED', 'HITL_APPROVED', 'HITL_REJECTED', 'HITL_QUEUED', 'FILE_CREATED', 'FILE_UPDATED', 'FILE_DELETED', 'FILE_SHARED', 'ORG_CREATED', 'ORG_UPDATED', 'ORG_MEMBER_ADDED', 'ORG_MEMBER_REMOVED', 'REPO_CREATED', 'REPO_PUSHED', 'REPO_SYNCED', 'BUILD_STARTED', 'BUILD_COMPLETED', 'BUILD_FAILED', name='auditeventtype'), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Enum('PROHIBITED', 'HIGH_RISK', 'LIMITED_RISK', 'MINIMAL_RISK', name='risklevel'), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('governance_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_event_timestamp', 'audit_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_audit_org_timestamp', 'audit_logs', ['organisation_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_risk_level'), 'audit_logs', ['risk_level'], unique=False)
    op.create_index(op.f('ix_audit_logs_system_id'), 'audit_logs', ['system_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_board_org', 'boards', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_boards_organisation_id'), 'boards', ['organisation_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('consent_type', sa.Enum('ANALYTICS', 'MARKETING', 'AI', 'DATA_PROCESSING', name='consenttype'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_consent_type'), 'consent_records', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('dpia_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_categories', sa.JSON(), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('safeguards_implemented', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpia_records_approval_status'), 'dpia_records', ['approval_status'], unique=False)
    op.create_index(op.f('ix_dpia_records_assessment_date'), 'dpia_records', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_dpia_records_next_review_date'), 'dpia_records', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_dpia_records_system_id'), 'dpia_records', ['system_id'], unique=True)
    op.create_table('file_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FILE', 'DIRECTORY', 'SYMLINK', name='filetype'), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('acl', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['file_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'path', name='uq_file_org_path')
    )
    op.create_index('idx_file_org', 'file_nodes', ['organisation_id'], unique=False)
    op.create_index('idx_file_path', 'file_nodes', ['path'], unique=False)
    op.create_index(op.f('ix_file_nodes_organisation_id'), 'file_nodes', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_file_nodes_owner_id'), 'file_nodes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_file_nodes_parent_id'), 'file_nodes', ['parent_id'], unique=False)
    op.create_table('hitl_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('proposed_output', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('PROHIBITED', 'HIGH_RISK', 'LIMITED_RISK', 'MINIMAL_RISK', name='risklevel'), nullable=False),
    sa.Column('status', sa.Enum('PROCESSED', 'PENDING_REVIEW', 'REJECTED', name='taskstatus'), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('manifest_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hitl_org_status', 'hitl_tasks', ['organisation_id', 'status'], unique=False)
    op.create_index('idx_hitl_status_created', 'hitl_tasks', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_created_at'), 'hitl_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_organisation_id'), 'hitl_tasks', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_risk_level'), 'hitl_tasks', ['risk_level'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_status'), 'hitl_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_submitted_by'), 'hitl_tasks', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_system_id'), 'hitl_tasks', ['system_id'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_task_type'), 'hitl_tasks', ['task_type'], unique=False)
    op.create_table('module_installations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manifest_id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('installed_by', sa.String(), nullable=False),
    sa.Column('granted_permissions', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['installed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manifest_id'], ['module_manifests.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_installations_organisation_id'), 'module_installations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_module_installations_user_id'), 'module_installations', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_module', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perm_user_scope', 'permissions', ['user_id', 'scope'], unique=False)
    op.create_index(op.f('ix_permissions_scope'), 'permissions', ['scope'], unique=False)
    op.create_index(op.f('ix_permissions_user_id'), 'permissions', ['user_id'], unique=False)
    op.create_table('provenance_manifests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('manifest_url', sa.String(), nullable=True),
    sa.Column('manifest_data', sa.JSON(), nullable=True),
    sa.Column('signing_status', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('idx_provenance_status', 'provenance_manifests', ['signing_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_provenance_manifests_content_hash'), 'provenance_manifests', ['content_hash'], unique=True)
    op.create_index(op.f('ix_provenance_manifests_created_at'), 'provenance_manifests', ['created_at'], unique=False)
    op.create_index(op.f('ix_provenance_manifests_organisation_id'), 'provenance_manifests', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_provenance_manifests_request_id'), 'provenance_manifests', ['request_id'], unique=False)
    op.create_index(op.f('ix_provenance_manifests_signing_status'), 'provenance_manifests', ['signing_status'], unique=False)
    op.create_index(op.f('ix_provenance_manifests_system_id'), 'provenance_manifests', ['system_id'], unique=False)
    op.create_index(op.f('ix_provenance_manifests_user_id'), 'provenance_manifests', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'INTERNAL', 'PUBLIC', name='repovisibility'), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('github_remote_url', sa.String(), nullable=True),
    sa.Column('github_sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('branch_count', sa.Integer(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'slug', name='uq_repo_org_slug')
    )
    op.create_index('idx_repo_org', 'repositories', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_repositories_organisation_id'), 'repositories', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('board_columns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('column_type', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'TESTING', 'DONE', 'ARCHIVED', name='boardcolumntype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_done_column', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_col_board_pos', 'board_columns', ['board_id', 'position'], unique=False)
    op.create_index(op.f('ix_board_columns_board_id'), 'board_columns', ['board_id'], unique=False)
    op.create_table('build_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('target', sa.Enum('PWA', 'ANDROID_APK', 'DESKTOP_ELECTRON', 'DESKTOP_TAURI', 'DOCKER', 'NPM_PACKAGE', 'PIP_PACKAGE', name='buildtarget'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'BUILDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='buildstatus'), nullable=True),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('build_command', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('artifact_url', sa.String(), nullable=True),
    sa.Column('artifact_size', sa.BigInteger(), nullable=True),
    sa.Column('build_log', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_build_org_status', 'build_jobs', ['organisation_id', 'status'], unique=False)
    op.create_index(op.f('ix_build_jobs_created_at'), 'build_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_build_jobs_organisation_id'), 'build_jobs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_build_jobs_repository_id'), 'build_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_build_jobs_status'), 'build_jobs', ['status'], unique=False)
    op.create_table('file_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'version', name='uq_file_version')
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_table('task_labels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_labels_board_id'), 'task_labels', ['board_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('column_id', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('STORY', 'BUG', 'TASK', 'EPIC', 'SUBTASK', 'SPIKE', name='tasktype'), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['column_id'], ['board_columns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_board_col', 'tasks', ['board_id', 'column_id'], unique=False)
    op.create_index('idx_task_key', 'tasks', ['key'], unique=False)
    op.create_index('idx_task_org_assignee', 'tasks', ['organisation_id', 'assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_board_id'), 'tasks', ['board_id'], unique=False)
    op.create_index(op.f('ix_tasks_column_id'), 'tasks', ['column_id'], unique=False)
    op.create_index(op.f('ix_tasks_key'), 'tasks', ['key'], unique=False)
    op.create_index(op.f('ix_tasks_organisation_id'), 'tasks', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_table('task_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('uploader_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attachments_task_id'), 'task_attachments', ['task_id'], unique=False)
    op.create_table('task_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.create_table('task_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_task_time', 'task_history', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index('idx_history_task_time', table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_task_attachments_task_id'), table_name='task_attachments')
    op.drop_table('task_attachments')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organisation_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_key'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_column_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_board_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index('idx_task_org_assignee', table_name='tasks')
    op.drop_index('idx_task_key', table_name='tasks')
    op.drop_index('idx_task_board_col', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_labels_board_id'), table_name='task_labels')
    op.drop_table('task_labels')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_build_jobs_status'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_repository_id'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_organisation_id'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_created_at'), table_name='build_jobs')
    op.drop_index('idx_build_org_status', table_name='build_jobs')
    op.drop_table('build_jobs')
    op.drop_index(op.f('ix_board_columns_board_id'), table_name='board_columns')
    op.drop_index('idx_col_board_pos', table_name='board_columns')
    op.drop_table('board_columns')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_organisation_id'), table_name='repositories')
    op.drop_index('idx_repo_org', table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_provenance_manifests_user_id'), table_name='provenance_manifests')
    op.drop_index(op.f('ix_provenance_manifests_system_id'), table_name='provenance_manifests')
    op.drop_index(op.f('ix_provenance_manifests_signing_status'), table_name='provenance_manifests')
    op.drop_index(op.f('ix_provenance_manifests_request_id'), table_name='provenance_manifests')
    op.drop_index(op.f('ix_provenance_manifests_organisation_id'), table_name='provenance_manifests')
    op.drop_index(op.f('ix_provenance_manifests_created_at'), table_name='provenance_manifests')
    op.drop_index(op.f('ix_provenance_manifests_content_hash'), table_name='provenance_manifests')
    op.drop_index('idx_provenance_status', table_name='provenance_manifests')
    op.drop_table('provenance_manifests')
    op.drop_index(op.f('ix_permissions_user_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_scope'), table_name='permissions')
    op.drop_index('idx_perm_user_scope', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_module_installations_user_id'), table_name='module_installations')
    op.drop_index(op.f('ix_module_installations_organisation_id'), table_name='module_installations')
    op.drop_table('module_installations')
    op.drop_index(op.f('ix_hitl_tasks_task_type'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_system_id'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_submitted_by'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_status'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_risk_level'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_organisation_id'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_created_at'), table_name='hitl_tasks')
    op.drop_index('idx_hitl_status_created', table_name='hitl_tasks')
    op.drop_index('idx_hitl_org_status', table_name='hitl_tasks')
    op.drop_table('hitl_tasks')
    op.drop_index(op.f('ix_file_nodes_parent_id'), table_name='file_nodes')
    op.drop_index(op.f('ix_file_nodes_owner_id'), table_name='file_nodes')
    op.drop_index(op.f('ix_file_nodes_organisation_id'), table_name='file_nodes')
    op.drop_index('idx_file_path', table_name='file_nodes')
    op.drop_index('idx_file_org', table_name='file_nodes')
    op.drop_table('file_nodes')
    op.drop_index(op.f('ix_dpia_records_system_id'), table_name='dpia_records')
    op.drop_index(op.f('ix_dpia_records_next_review_date'), table_name='dpia_records')
    op.drop_index(op.f('ix_dpia_records_assessment_date'), table_name='dpia_records')
    op.drop_index(op.f('ix_dpia_records_approval_status'), table_name='dpia_records')
    op.drop_table('dpia_records')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_consent_type'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_boards_organisation_id'), table_name='boards')
    op.drop_index('idx_board_org', table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_system_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_risk_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('idx_audit_org_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_event_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organisation_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_org_active', table_name='users')
    op.drop_index('idx_user_deleted', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index(op.f('ix_federated_services_organisation_id'), table_name='federated_services')
    op.drop_index('idx_fed_org_type', table_name='federated_services')
    op.drop_table('federated_services')
    op.drop_table('app_store_listings')
    op.drop_index(op.f('ix_ai_systems_risk_level'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_organisation_id'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_name'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_dpia_completed'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_created_at'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_compliance_status'), table_name='ai_systems')
    op.drop_index('idx_ai_system_org_status', table_name='ai_systems')
    op.drop_table('ai_systems')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_is_active'), table_name='organisations')
    op.drop_index('idx_org_deleted', table_name='organisations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('organisations')
    op.drop_index(op.f('ix_module_manifests_module_id'), table_name='module_manifests')
    op.drop_index(op.f('ix_module_manifests_category'), table_name='module_manifests')
    op.drop_table('module_manifests')
    # ### end Alembic commands ###
